### ISSUE TITLE
Error when creating new Social group

### ISSUE THREAD

**Issue by bruceMacLeod** [OpenHDS/ionic-client#52]
Social Group creation worked, but when I went to create the head. I get this error : 

<img width="864" alt="screen shot 2018-08-29 at 10 06 09 am" src="https://user-images.githubusercontent.com/1298797/44793066-5f1b1800-ab73-11e8-8454-fdfbf4679d21.png">

**Comment by littlefieldnick** [comment]
The error is caused by not being able to find a fieldworker to attach to the collectedBy field. Implementing user roles to distinguish admin from fieldworkers, and a mechanism to search for a fieldworker for the baseline census if an admin should fix it.
